# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install System require depedencies
        run: |
          sudo apt upgrade
          sudo apt install -y lsb-release sudo
          sudo apt install -y openssh-client git python
        
      - name: Install depo_tools
        run: |
          sudo mkdir /workspace
          sudo cd /workspace
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:/workspace/depot_tools"
      
      - name: Get chromium code
        run: |
          mkdir /workspace/chromium
          cd /workspace/chromium
          fetch --nohooks chromium
      
      - name: Install build deps
        run: |
          cd /workspace/chromium/src
          ./build/install-build-deps.sh --no-chromeos-fonts

      - name: Build chromedriver
        run: |
          cd /workspace/chromium/src
          gn gen out/Default
          autoninja -C out/Default chromedriver
          
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: chromedriver
      #     path: path/to/artifact

      - name: Display structure of downloaded files
        run: ls -R 
        working-directory: /workspace/chromium/src/out/Default