# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Initialization environment
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt upgrade
          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
          sudo -E apt-get -qq autoremove --purge
          sudo mkdir /workspace
          sudo chown $USER:$GROUPS /workspace

      - name: Install depo_tools
        working-directory: /workspace
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:/workspace/depot_tools"
      
      - name: Get chromium code
        working-directory: /workspace
        run: |
          export PATH="$PATH:/workspace/depot_tools"
          mkdir ./chromium
          cd ./chromium
          fetch --nohooks --no-history chromium 

      # - name: Update call_function.js
      #   run: |
      #     echo 'foo'

      - name: Install build deps
        working-directory: /workspace/chromium/src
        run: |
          export PATH="$PATH:/workspace/depot_tools"
          ./build/install-build-deps.sh --no-chromeos-fonts

      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@v1.0.0
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          

      - name: Build chromedriver
        working-directory: /workspace/chromium/src
        run: |
          export PATH="$PATH:/workspace/depot_tools"
          gn gen out/Default
          autoninja -C out/Default chromedriver
          
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: chromedriver
      #     path: path/to/artifact

      - name: Display structure of downloaded files
        working-directory: /workspace/chromium/src/out/Default
        run: ls -R 
        